<?php

/*

  SWIFT MAILER REQUIRED
  ---------------------

  sudo apt-get install php-pear

  sudo pear channel-discover pear.swiftmailer.org

  sudo pear install swift/swift

*/


// 1) Setup swift mailer transport 
require_once 'swift_required.php';
$transport = Swift_SmtpTransport::newInstance('mail.yourserver.com', 26)
  ->setUsername('username')
  ->setPassword('password')
;
// Create the Mailer using your created Transport
$mailer = Swift_Mailer::newInstance($transport);

// Retrieve apikey (needed to get feed list)
$url = "http://localhost/emoncms/raspberrypi/get.json";
$content = file_get_contents($url);
$json = json_decode($content,true);
$userid = $json['userid'];
$apikey = $json['apikey'];
$count = 0;

// 2) Determine feeds
$url = "http://localhost/emoncms/feed/list.json?apikey=$apikey";
$content = file_get_contents($url);
$json = json_decode($content,true);
$h24 = time() - (3600*2);
$h48 = time() - (3600*4);
$body = "<p><b>Hello!</b></p><p>The following emoncms feeds have become inactive for more than 2 hours:</p><ul>";
foreach($json as $item) 
	{
	if ($item['time']>=$h48 && $item['time']<=$h24)
		{
		$body .= "<li>".$item['name']."</li>";
		++$count;
		}
	}
echo $count;
if ($count > 0)
	{
	$mysqli = new mysqli("localhost","username","password","database");

	$result = $mysqli->query("SELECT email FROM notify WHERE `userid` = '$userid' AND `enabled` = '1';"); 
	$row = mysqli_fetch_array($result);
	$email = $row['email'];
	$body .= "</ul>";
	$body .= "<p><i>This is an automated email generated by the emoncms notify module. To turn 'notify on inactive'  off click on disable on the notify module page.</i></p>";
	$mail = new PHPMailer();
	$mail->SetFrom("from@example.com", "Emoncms");
	$mail->AddAddress($email, "FirstName LastName");
	$mail->Subject = "$count emoncms feeds have become inactive";
	$mail->MsgHTML($body);
	if(!$mail->Send()) 
		{
		echo "Mailer Error: " . $mail->ErrorInfo;
		}
	else
		{
		echo "Message sent!";
		}
	}
?>
