<?php

/*

  PHP mail() implementation, may not be 100% reliable 
  but does not require smtp or other complicated setup
  out of the box.

*/  

define('EMONCMS_EXEC', 1);

chdir("/var/www/emoncms");

require "process_settings.php";
$mysqli = @new mysqli($server,$username,$password,$database);

$redis = new Redis();
$redis->connect("127.0.0.1");


// 2) Determine feeds
$now = time();
$h24 = $now - (3600*2); // 2 hours
$h48 = $now - (3600*4); // 4 hours
 
$keys = $redis->keys("feed:lastvalue:*");

$users = array();

foreach ($keys as $key)
{
  $parts = explode(":",$key);
  $feedid = $parts[2];
  $time = strtotime($redis->hget("feed:lastvalue:$feedid","time"));
  
  if ($time>=$h48 && $time<=$h24)
  {
    // fetch userid
    
    $result = $mysqli->query("SELECT name, userid FROM feeds WHERE `id`='$feedid'");
    $row = $result->fetch_array();
    $userid = $row['userid'];
    if (!isset($users[$row['userid']])) $users[$userid] = array('id'=>$userid, 'feeds'=>array());
    $users[$userid]['feeds'][] = $row['name'];
  }
}

foreach ($users as $user)
{

  $userid = $user['id'];
  $result = $mysqli->query("SELECT email FROM notify WHERE `userid` = '$userid' AND `enabled` = '1';");
  
  
  if ($result && $result->num_rows)
  {  
    $row = $result->fetch_array();
    $email = $row['email'];
    
    // Send an email
    
    $body = "<p><b>Hello!</b></p><p>The following emoncms feeds have become inactive for more than 2 hours:</p><ul>";
    foreach ($user['feeds'] as $feed)
    {
      $body .= "<li>".$feed."</li>";
    }
    $body .= "</ul>";
    $body .= "<p><i>This is an automated email generated by the emoncms notify module. To turn 'notify on inactive' off click on disable on the notify module page</i></p>";

    // To send HTML mail, the Content-type header must be set
    $headers  = 'MIME-Version: 1.0' . "\r\n";
    $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

    // Additional headers
    $headers .= 'From: emoncms' . "\r\n";

    $subject = count($user['feeds'])." emoncms feeds have become inactive";
    // Mail it
    mail($email, $subject, $body, $headers);
  }
}
